import React from 'react';
import TreeView from './components/TreeView';
import './App.css';

function App() {
  // The data prop passed to the TreeView component should be an array of node objects.
  // Each node object has the following structure:
  // {
  //   id: PropTypes.string.isRequired,
  //   name: PropTypes.string.isRequired,
  //   children: PropTypes.array, // Array of node objects
  //   properties: PropTypes.object.isRequired,
  // }
  const data = [
    {
      id: 'root',
      name: 'root',
      properties: {
        size: '100MB',
        type: 'folder',
        created: '2023-01-01',
        modified: '2023-01-15',
        owner: 'admin',
        group: 'admin',
        permissions: 'rwxr-xr-x',
        checksum: 'N/A',
        version: '1.0',
        author: 'system',
      },
      children: [
        {
          id: '1',
          name: 'folder1',
          properties: {
            size: '50MB',
            type: 'folder',
            created: '2023-01-02',
            modified: '2023-01-10',
            owner: 'admin',
            group: 'admin',
            permissions: 'rwxr-xr-x',
            checksum: 'N/A',
            version: '1.0',
            author: 'system',
          },
          children: [
            {
              id: '3',
              name: 'file1.txt',
              properties: {
                size: '10MB',
                type: 'file',
                created: '2023-01-03',
                modified: '2023-01-05',
                owner: 'user1',
                group: 'users',
                permissions: 'rw-r--r--',
                checksum: 'md5:abcde12345',
                version: '1.1',
                author: 'user1',
              },
            },
            {
              id: '4',
              name: 'file4.txt',
              properties: {
                size: '1MB',
                type: 'file',
                created: '2023-01-04',
                modified: '2023-01-11',
                owner: 'user2',
                group: 'users',
                permissions: 'rw-r--r--',
                checksum: 'md5:12345abcde',
                version: '1.0',
                author: 'user2',
              },
            },
            {
              id: '5',
              name: 'file5.txt',
              properties: {
                size: '5MB',
                type: 'file',
                created: '2023-01-05',
                modified: '2023-01-12',
                owner: 'user3',
                group: 'users',
                permissions: 'rw-r--r--',
                checksum: 'md5:abcde54321',
                version: '1.0',
                author: 'user3',
              },
            },
            {
              id: '6',
              name: 'file6.txt',
              properties: {
                size: '2MB',
                type: 'file',
                created: '2023-01-06',
                modified: '2023-01-13',
                owner: 'user1',
                group: 'users',
                permissions: 'rw-r--r--',
                checksum: 'md5:54321abcde',
                version: '1.0',
                author: 'user1',
              },
            },
            {
              id: '7',
              name: 'file7.txt',
              properties: {
                size: '3MB',
                type: 'file',
                created: '2023-01-07',
                modified: '2023-01-14',
                owner: 'user2',
                group: 'users',
                permissions: 'rw-r--r--',
                checksum: 'md5:ab12345cde',
                version: '1.0',
                author: 'user2',
              },
            },
            {
              id: '8',
              name: 'file8.txt',
              properties: {
                size: '4MB',
                type: 'file',
                created: '2023-01-08',
                modified: '2023-01-15',
                owner: 'user3',
                group: 'users',
                permissions: 'rw-r--r--',
                checksum: 'md5:12345ab_cde',
                version: '1.0',
                author: 'user3',
              },
            },
            {
              id: '9',
              name: 'file9.txt',
              properties: {
                size: '6MB',
                type: 'file',
                created: '2023-01-09',
                modified: '2023-01-16',
                owner: 'user1',
                group: 'users',
                permissions: 'rw-r--r--',
                checksum: 'md5:cde12345ab',
                version: '1.0',
                author: 'user1',
              },
            },
            {
              id: '10',
              name: 'file10.txt',
              properties: {
                size: '7MB',
                type: 'file',
                created: '2023-01-10',
                modified: '2023-01-17',
                owner: 'user2',
                group: 'users',
                permissions: 'rw-r--r--',
                checksum: 'md5:ab_cde12345',
                version: '1.0',
                author: 'user2',
              },
            },
            {
              id: '11',
              name: 'file11.txt',
              properties: {
                size: '8MB',
                type: 'file',
                created: '2023-01-11',
                modified: '2023-01-18',
                owner: 'user3',
                group: 'users',
                permissions: 'rw-r--r--',
                checksum: 'md5:123ab_cde45',
                version: '1.0',
                author: 'user3',
              },
            },
            {
              id: '12',
              name: 'file12.txt',
              properties: {
                size: '9MB',
                type: 'file',
                created: '2023-01-12',
                modified: '2023-01-19',
                owner: 'user1',
                group: 'users',
                permissions: 'rw-r--r--',
                checksum: 'md5:cdeab12345',
                version: '1.0',
                author: 'user1',
              },
            },
            {
              id: '13',
              name: 'file13.txt',
              properties: {
                size: '11MB',
                type: 'file',
                created: '2023-01-13',
                modified: '2023-01-20',
                owner: 'user2',
                group: 'users',
                permissions: 'rw-r--r--',
                checksum: 'md5:12345cde_ab',
                version: '1.0',
                author: 'user2',
              },
            },
            {
              id: '14',
              name: 'file14.txt',
              properties: {
                size: '12MB',
                type: 'file',
                created: '2023-01-14',
                modified: '2023-01-21',
                owner: 'user3',
                group: 'users',
                permissions: 'rw-r--r--',
                checksum: 'md5:ab_cde54321',
                version: '1.0',
                author: 'user3',
              },
            },
            {
              id: '15',
              name: 'file15.txt',
              properties: {
                size: '13MB',
                type: 'file',
                created: '2023-01-15',
                modified: '2023-01-22',
                owner: 'user1',
                group: 'users',
                permissions: 'rw-r--r--',
                checksum: 'md5:54321ab_cde',
                version: '1.0',
                author: 'user1',
              },
            },
            {
              id: '16',
              name: 'file16.txt',
              properties: {
                size: '14MB',
                type: 'file',
                created: '2023-01-16',
                modified: '2023-01-23',
                owner: 'user2',
                group: 'users',
                permissions: 'rw-r--r--',
                checksum: 'md5:cde_ab12345',
                version: '1.0',
                author: 'user2',
              },
            },
            {
              id: '17',
              name: 'file17.txt',
              properties: {
                size: '15MB',
                type: 'file',
                created: '2023-01-17',
                modified: '2023-01-24',
                owner: 'user3',
                group: 'users',
                permissions: 'rw-r--r--',
                checksum: 'md5:12345ab_cde',
                version: '1.0',
                author: 'user3',
              },
            },
            {
              id: '18',
              name: 'file18.txt',
              properties: {
                size: '16MB',
                type: 'file',
                created: '2023-01-18',
                modified: '2023-01-25',
                owner: 'user1',
                group: 'users',
                permissions: 'rw-r--r--',
                checksum: 'md5:ab_cde12345',
                version: '1.0',
                author: 'user1',
              },
            },
            {
              id: '19',
              name: 'file19.txt',
              properties: {
                size: '17MB',
                type: 'file',
                created: '2023-01-19',
                modified: '2023-01-26',
                owner: 'user2',
                group: 'users',
                permissions: 'rw-r--r--',
                checksum: 'md5:cde12345ab',
                version: '1.0',
                author: 'user2',
              },
            },
            {
              id: '20',
              name: 'file20.txt',
              properties: {
                size: '18MB',
                type: 'file',
                created: '2023-01-20',
                modified: '2023-01-27',
                owner: 'user3',
                group: 'users',
                permissions: 'rw-r--r--',
                checksum: 'md5:123ab_cde45',
                version: '1.0',
                author: 'user3',
              },
            },
            {
              id: '21',
              name: 'file21.txt',
              properties: {
                size: '19MB',
                type: 'file',
                created: '2023-01-21',
                modified: '2023-01-28',
                owner: 'user1',
                group: 'users',
                permissions: 'rw-r--r--',
                checksum: 'md5:cdeab12345',
                version: '1.0',
                author: 'user1',
              },
            },
            {
              id: '22',
              name: 'file22.txt',
              properties: {
                size: '20MB',
                type: 'file',
                created: '2023-01-22',
                modified: '2023-01-29',
                owner: 'user2',
                group: 'users',
                permissions: 'rw-r--r--',
                checksum: 'md5:12345cde_ab',
                version: '1.0',
                author: 'user2',
              },
            },
            {
              id: '23',
              name: 'file23.txt',
              properties: {
                size: '21MB',
                type: 'file',
                created: '2023-01-23',
                modified: '2023-01-30',
                owner: 'user3',
                group: 'users',
                permissions: 'rw-r--r--',
                checksum: 'md5:ab_cde54321',
                version: '1.0',
                author: 'user3',
              },
            },
            {
              id: '24',
              name: 'file24.txt',
              properties: {
                size: '22MB',
                type: 'file',
                created: '2023-01-24',
                modified: '2023-01-31',
                owner: 'user1',
                group: 'users',
                permissions: 'rw-r--r--',
                checksum: 'md5:54321ab_cde',
                version: '1.0',
                author: 'user1',
              },
            },
          ],
        },
        {
          id: '2',
          name: 'file2.txt',
          properties: {
            size: '20MB',
            type: 'file',
            created: '2023-01-04',
            modified: '2023-01-06',
            owner: 'user2',
            group: 'users',
            permissions: 'rw-r--r--',
            checksum: 'md5:fghij67890',
            version: '1.0',
            author: 'user2',
          },
        },
        {
          id: '25',
          name: 'folder2',
          properties: {
            size: '75MB',
            type: 'folder',
            created: '2023-02-01',
            modified: '2023-02-15',
            owner: 'admin',
            group: 'admin',
            permissions: 'rwxr-xr-x',
            checksum: 'N/A',
            version: '1.0',
            author: 'system',
          },
          children: [
            {
              id: '26',
              name: 'file26.txt',
              properties: {
                size: '10MB',
                type: 'file',
                created: '2023-02-03',
                modified: '2023-02-05',
                owner: 'user1',
                group: 'users',
                permissions: 'rw-r--r--',
                checksum: 'md5:abcdef12345',
                version: '1.1',
                author: 'user1',
              },
            },
            {
              id: '27',
              name: 'file27.txt',
              properties: {
                size: '5MB',
                type: 'file',
                created: '2023-02-04',
                modified: '2023-02-11',
                owner: 'user2',
                group: 'users',
                permissions: 'rw-r--r--',
                checksum: 'md5:12345abcdef',
                version: '1.0',
                author: 'user2',
              },
            },
            {
              id: '28',
              name: 'file28.txt',
              properties: {
                size: '2MB',
                type: 'file',
                created: '2023-02-05',
                modified: '2023-02-12',
                owner: 'user3',
                group: 'users',
                permissions: 'rw-r--r--',
                checksum: 'md5:abcdef54321',
                version: '1.0',
                author: 'user3',
              },
            },
            {
              id: '29',
              name: 'file29.txt',
              properties: {
                size: '3MB',
                type: 'file',
                created: '2023-02-06',
                modified: '2023-02-13',
                owner: 'user1',
                group: 'users',
                permissions: 'rw-r--r--',
                checksum: 'md5:54321abcdef',
                version: '1.0',
                author: 'user1',
              },
            },
            {
              id: '30',
              name: 'file30.txt',
              properties: {
                size: '4MB',
                type: 'file',
                created: '2023-02-07',
                modified: '2023-02-14',
                owner: 'user2',
                group: 'users',
                permissions: 'rw-r--r--',
                checksum: 'md5:ab12345cdef',
                version: '1.0',
                author: 'user2',
              },
            },
            {
              id: '31',
              name: 'file31.txt',
              properties: {
                size: '6MB',
                type: 'file',
                created: '2023-02-08',
                modified: '2023-02-15',
                owner: 'user3',
                group: 'users',
                permissions: 'rw-r--r--',
                checksum: 'md5:12345ab_cdef',
                version: '1.0',
                author: 'user3',
              },
            },
            {
              id: '32',
              name: 'file32.txt',
              properties: {
                size: '7MB',
                type: 'file',
                created: '2023-02-09',
                modified: '2023-02-16',
                owner: 'user1',
                group: 'users',
                permissions: 'rw-r--r--',
                checksum: 'md5:cdef12345ab',
                version: '1.0',
                author: 'user1',
              },
            },
            {
              id: '33',
              name: 'file33.txt',
              properties: {
                size: '8MB',
                type: 'file',
                created: '2023-02-10',
                modified: '2023-02-17',
                owner: 'user2',
                group: 'users',
                permissions: 'rw-r--r--',
                checksum: 'md5:ab_cdef12345',
                version: '1.0',
                author: 'user2',
              },
            },
            {
              id: '34',
              name: 'file34.txt',
              properties: {
                size: '9MB',
                type: 'file',
                created: '2023-02-11',
                modified: '2023-02-18',
                owner: 'user3',
                group: 'users',
                permissions: 'rw-r--r--',
                checksum: 'md5:123ab_cdef45',
                version: '1.0',
                author: 'user3',
              },
            },
            {
              id: '35',
              name: 'file35.txt',
              properties: {
                size: '11MB',
                type: 'file',
                created: '2023-02-12',
                modified: '2023-02-19',
                owner: 'user1',
                group: 'users',
                permissions: 'rw-r--r--',
                checksum: 'md5:cdefab12345',
                version: '1.0',
                author: 'user1',
              },
            },
            {
              id: '36',
              name: 'file36.txt',
              properties: {
                size: '12MB',
                type: 'file',
                created: '2023-02-13',
                modified: '2023-02-20',
                owner: 'user2',
                group: 'users',
                permissions: 'rw-r--r--',
                checksum: 'md5:12345cdef_ab',
                version: '1.0',
                author: 'user2',
              },
            },
            {
              id: '37',
              name: 'file37.txt',
              properties: {
                size: '13MB',
                type: 'file',
                created: '2023-02-14',
                modified: '2023-02-21',
                owner: 'user3',
                group: 'users',
                permissions: 'rw-r--r--',
                checksum: 'md5:ab_cdef54321',
                version: '1.0',
                author: 'user3',
              },
            },
            {
              id: '38',
              name: 'file38.txt',
              properties: {
                size: '14MB',
                type: 'file',
                created: '2023-02-15',
                modified: '2023-02-22',
                owner: 'user1',
                group: 'users',
                permissions: 'rw-r--r--',
                checksum: 'md5:54321ab_cdef',
                version: '1.0',
                author: 'user1',
              },
            },
            {
              id: '39',
              name: 'file39.txt',
              properties: {
                size: '15MB',
                type: 'file',
                created: '2023-02-16',
                modified: '2023-02-23',
                owner: 'user2',
                group: 'users',
                permissions: 'rw-r--r--',
                checksum: 'md5:cdef_ab12345',
                version: '1.0',
                author: 'user2',
              },
            },
            {
              id: '40',
              name: 'file40.txt',
              properties: {
                size: '16MB',
                type: 'file',
                created: '2023-02-17',
                modified: '2023-02-24',
                owner: 'user3',
                group: 'users',
                permissions: 'rw-r--r--',
                checksum: 'md5:12345ab_cdef',
                version: '1.0',
                author: 'user3',
              },
            },
            {
              id: '41',
              name: 'file41.txt',
              properties: {
                size: '17MB',
                type: 'file',
                created: '2023-02-18',
                modified: '2023-02-25',
                owner: 'user1',
                group: 'users',
                permissions: 'rw-r--r--',
                checksum: 'md5:ab_cdef12345',
                version: '1.0',
                author: 'user1',
              },
            },
            {
              id: '42',
              name: 'file42.txt',
              properties: {
                size: '18MB',
                type: 'file',
                created: '2023-02-19',
                modified: '2023-02-26',
                owner: 'user2',
                group: 'users',
                permissions: 'rw-r--r--',
                checksum: 'md5:cdef12345ab',
                version: '1.0',
                author: 'user2',
              },
            },
            {
              id: '43',
              name: 'file43.txt',
              properties: {
                size: '19MB',
                type: 'file',
                created: '2023-02-20',
                modified: '2023-02-27',
                owner: 'user3',
                group: 'users',
                permissions: 'rw-r--r--',
                checksum: 'md5:123ab_cdef45',
                version: '1.0',
                author: 'user3',
              },
            },
            {
              id: '44',
              name: 'file44.txt',
              properties: {
                size: '20MB',
                type: 'file',
                created: '2023-02-21',
                modified: '2023-02-28',
                owner: 'user1',
                group: 'users',
                permissions: 'rw-r--r--',
                checksum: 'md5:cdefab12345',
                version: '1.0',
                author: 'user1',
              },
            },
            {
              id: '45',
              name: 'file45.txt',
              properties: {
                size: '21MB',
                type: 'file',
                created: '2023-02-22',
                modified: '2023-03-01',
                owner: 'user2',
                group: 'users',
                permissions: 'rw-r--r--',
                checksum: 'md5:12345cdef_ab',
                version: '1.0',
                author: 'user2',
              },
            },
            {
              id: '46',
              name: 'file46.txt',
              properties: {
                size: '22MB',
                type: 'file',
                created: '2023-02-23',
                modified: '2023-03-02',
                owner: 'user3',
                group: 'users',
                permissions: 'rw-r--r--',
                checksum: 'md5:ab_cdef54321',
                version: '1.0',
                author: 'user3',
              },
            },
            {
              id: '47',
              name: 'file47.txt',
              properties: {
                size: '23MB',
                type: 'file',
                created: '2023-02-24',
                modified: '2023-03-03',
                owner: 'user1',
                group: 'users',
                permissions: 'rw-r--r--',
                checksum: 'md5:54321ab_cdef',
                version: '1.0',
                author: 'user1',
              },
            },
            {
              id: '48',
              name: 'file48.txt',
              properties: {
                size: '24MB',
                type: 'file',
                created: '2023-02-25',
                modified: '2023-03-04',
                owner: 'user2',
                group: 'users',
                permissions: 'rw-r--r--',
                checksum: 'md5:cdef_ab12345',
                version: '1.0',
                author: 'user2',
              },
            },
            {
              id: '49',
              name: 'file49.txt',
              properties: {
                size: '25MB',
                type: 'file',
                created: '2023-02-26',
                modified: '2023-03-05',
                owner: 'user3',
                group: 'users',
                permissions: 'rw-r--r--',
                checksum: 'md5:12345ab_cdef',
                version: '1.0',
                author: 'user3',
              },
            },
          ],
        },
      ],
    },
  ];

  return (
    <div className="App">
      <h1>File System Tree View</h1>
      <TreeView data={data} />
    </div>
  );
}

export default App;
